services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/website:/usr/share/nginx/html
    depends_on:
      - app1
      - app2
      - app3
  app1:
    build: ./app 
    ports:
      - "3001:3000"
    depends_on:
      - db
  app2:
    build: ./app 
    ports:
      - "3002:3000"
    depends_on:
      - db
  app3:
    build: ./app 
    ports:
      - "3003:3000"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password  
      MYSQL_DATABASE: lms_db               
      MYSQL_USER: admin                    
      MYSQL_PASSWORD: qwerty               
    ports:
      - "3306:3306"                         
    volumes:
      - mysql_data:/var/lib/mysql
  file_storage:
    build: ./file_storage
    volumes:
      - uploads:/usr/src/app/uploads
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: qwerty
    depends_on:
      - db
volumes:
  mysql_data:
  uploads: