pipeline {
    agent any

    stages {
        stage('Checkout') {
          steps {
            git url: 'https://github.com/roman23323/LMS-project', branch: 'main'
          }
        }
        stage('Build') {
            steps {
                sh 'docker-compose build' // Сборка образов
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker-compose up -d' // Запуск всех контейнеров
            }
        }
        stage('Test') {
            steps {
                sh 'mocha tests/test.js' // Запуск тестов
            }
        }
        stage('Cleanup') {
            steps {
                sh 'docker-compose down' // Остановка и удаление контейнеров
            }
        }
    }
}